/*
  types:
    infection
    action
    defence
    map    
    panic
*/

const cards = [
  { 
    id: 1,
    media: 'AgACAgQAAxkDAAIEDF6eyxcjcj8ysccaAtLiE8ljZWKhAALlqjEb84X9UNxGT53kcAQWrSR5I10AAwEAAwIAA20AAxSAAAIYBA',
    type: 'the_thing',
    name: 'Нечто',
    description: 'Вы должны заразить других!',
    players: 4,
    isStayAway: true,
  }, {
    id: 2,
    media: 'AgACAgQAAxkDAAIEDV6eyxgJyT5I7V8W9dFFl0H0VI6oAAIMqzEbeNr0UM7EBHshF1DlMCq2GwAEAQADAgADbQADOsAFAAEYBA',
    type: 'infection',
    name: 'Заражение!',
    description: 'Получив эту карту от другого игрока, вы становитесь зараженным и обязаны держать её на руке до конца игры.',
    isInfection: true,
    players: 4,
  }, {
    id: 3,
    media: 'AgACAgQAAxkDAAIEDl6eyxjnZ75evgH8hK2DwUq9Y3YPAAKxqjEbOzL8UJR4mXe75UPFWYD6Il0AAwEAAwIAA20AA3MNAQABGAQ',
    type: 'infection',
    name: 'Заражение!',
    description: 'Получив эту карту от другого игрока, вы становитесь зараженным и обязаны держать её на руке до конца игры.',
    isInfection: true
  }, {
    id: 4,
    media: 'AgACAgQAAxkDAAIED16eyxg67KmpJWKulWp8_X7Msr4FAAIFqzEbiKT8UHZIxVd6dtRJyToII10AAwEAAwIAA20AA8ipAAIYBA',
    type: 'infection',
    name: 'Заражение!',
    description: 'Получив эту карту от другого игрока, вы становитесь зараженным и обязаны держать её на руке до конца игры.',
    isInfection: true
  }, {
    id: 5,
    media: 'AgACAgQAAxkDAAIEEF6eyxmAuPyhF_IT3mfVsVQyHvjtAAIYqzEbekv1UNBL1rFur7jndzSRIl0AAwEAAwIAA20AA-x4AgABGAQ',
    type: 'infection',
    name: 'Заражение!',
    description: 'Получив эту карту от другого игрока, вы становитесь зараженным и обязаны держать её на руке до конца игры.',
    isInfection: true
  }, {
    id: 6,
    media: 'AgACAgQAAxkDAAIEEV6eyxkfUftNsdPNUv4_Dw7poP5tAALvqjEb51L9UAERZ5tVdjgwj7h9I10AAwEAAwIAA20AA92BAAIYBA',
    type: 'infection',
    name: 'Заражение!',
    description: 'Получив эту карту от другого игрока, вы становитесь зараженным и обязаны держать её на руке до конца игры.',
    isInfection: true
  }, {
    id: 7,
    media: 'AgACAgQAAxkDAAIEEl6eyxlVjV85LxV0K-qXYHRxIUjaAAIpqzEbacH1UEUyx0427vRjwgyIIl0AAwEAAwIAA20AA0R0AgABGAQ',
    type: 'infection',
    name: 'Заражение!',
    description: 'Получив эту карту от другого игрока, вы становитесь зараженным и обязаны держать её на руке до конца игры.',
    isInfection: true
  }, {
    id: 8,
    media: 'AgACAgQAAxkDAAIEE16eyxpruzAmMCTPDlcu8EeJijaqAALqqjEbsXT8UIBCG-enaEIHC479Il0AAwEAAwIAA20AA1MLAQABGAQ',
    type: 'infection',
    name: 'Заражение!',
    description: 'Получив эту карту от другого игрока, вы становитесь зараженным и обязаны держать её на руке до конца игры.',
    isInfection: true
  }, {
    id: 9,
    media: 'AgACAgQAAxkDAAIEFF6eyxqo7PLpTRsx1qu-_jQ5tithAALaqjEbjm71UJ_wYExwQuRy72P0Il0AAwEAAwIAA20AAzynAAIYBA',
    type: 'infection',
    name: 'Заражение!',
    description: 'Получив эту карту от другого игрока, вы становитесь зараженным и обязаны держать её на руке до конца игры.',
    isInfection: true
  }, {
    id: 10,
    media: 'AgACAgQAAxkDAAIEFV6eyxpq8xSY80KmKJVbrNh3heqkAAIwqzEbJPr1UNm60HdKQjHzQRbiIl0AAwEAAwIAA20AAxURAQABGAQ',
    type: 'infection',
    name: 'Заражение!',
    description: 'Получив эту карту от другого игрока, вы становитесь зараженным и обязаны держать её на руке до конца игры.',
    isInfection: true,
    players: 6,
    ability: '',
  }, {
    id: 11,
    media: 'AgACAgQAAxkDAAIEFl6eyxuBGSN7PEG6UQtWeVm6_8YcAALBqjEbj7X9UMyLEZku1LL2Z5-0GwAEAQADAgADbQADqMMFAAEYBA',
    type: 'infection',
    name: 'Заражение!',
    description: 'Получив эту карту от другого игрока, вы становитесь зараженным и обязаны держать её на руке до конца игры.',
    isInfection: true,
    players: 7,
    ability: '',
  }, {
    id: 12,
    media: 'AgACAgQAAxkDAAIEF16eyxxjdYQgeYZbir_pO-eUpvNRAALmqjEbiaj9UCNrdltWViv1jNUgGwAEAQADAgADbQADszEHAAEYBA',
    type: 'infection',
    name: 'Заражение!',
    description: 'Получив эту карту от другого игрока, вы становитесь зараженным и обязаны держать её на руке до конца игры.',
    isInfection: true,
    players: 7,
    ability: '',
  }, {
    id: 13,
    media: 'AgACAgQAAxkDAAIEGF6eyx12U9HCdu6HKObS2ulZnwp9AAL2qjEbD9j9UDc_6cVLcqIQLIa3GwAEAQADAgADbQADHLsFAAEYBA',
    type: 'infection',
    name: 'Заражение!',
    description: 'Получив эту карту от другого игрока, вы становитесь зараженным и обязаны держать её на руке до конца игры.',
    isInfection: true,
    players: 7,
    ability: '',
  }, {
    id: 14,
    media: 'AgACAgQAAxkDAAIEGV6eyx6RoafAQus_X6-ocw9aWCIjAAL-qjEbj571UCHLBQAB0TohjmBY8SJdAAMBAAMCAANtAAO5qAACGAQ',
    type: 'infection',
    name: 'Заражение!',
    description: 'Получив эту карту от другого игрока, вы становитесь зараженным и обязаны держать её на руке до конца игры.',
    isInfection: true,
    players: 8,
    ability: '',
  }, {
    id: 15,
    media: 'AgACAgQAAxkDAAIEGl6eyx_VW_86PPDLjZvVeZ6A05BoAALkqjEb2MD8UCb7HE2Vu1UejwnfIl0AAwEAAwIAA20AA-kJAQABGAQ',
    type: 'infection',
    name: 'Заражение!',
    description: 'Получив эту карту от другого игрока, вы становитесь зараженным и обязаны держать её на руке до конца игры.',
    isInfection: true,
    players: 9,
    ability: '',
  }, {
    id: 16,
    media: 'AgACAgQAAxkDAAIEG16eyyEXlK5ug0LqudiM09AZTkZzAAIjqzEbuHb0UHCUZ_6EfT_7n4D6Il0AAwEAAwIAA20AAw0PAQABGAQ',
    type: 'infection',
    name: 'Заражение!',
    description: 'Получив эту карту от другого игрока, вы становитесь зараженным и обязаны держать её на руке до конца игры.',
    isInfection: true,
    players: 9,
    ability: '',
  }, {
    id: 17,
    media: 'AgACAgQAAxkDAAIEHF6eyyID17gpIKaUxWxmXDgaAAEWDgAC2qoxGy1c_VDkY78oocNtbEmHhiJdAAMBAAMCAANtAANkeQIAARgE',
    type: 'infection',
    name: 'Заражение!',
    description: 'Получив эту карту от другого игрока, вы становитесь зараженным и обязаны держать её на руке до конца игры.',
    isInfection: true,
    players: 10,
    ability: '',
  }, {
    id: 18,
    media: 'AgACAgQAAxkDAAIEHV6eyyP8QhOK8ponDsvhvW-_DB_sAAKxqjEbPRn9UKuPGjERCIbFiXLaIl0AAwEAAwIAA20AA74LAQABGAQ',
    type: 'infection',
    name: 'Заражение!',
    description: 'Получив эту карту от другого игрока, вы становитесь зараженным и обязаны держать её на руке до конца игры.',
    isInfection: true,
    players: 10,
    ability: '',
  }, {
    id: 19,
    media: 'AgACAgQAAxkDAAIEHl6eyzhr4NQg7jIW--tD-Gh3gFUcAALKqjEbXND8UMzyN24sWWvRpu3YIl0AAwEAAwIAA20AA24NAQABGAQ',
    type: 'infection',
    name: 'Заражение!',
    description: 'Получив эту карту от другого игрока, вы становитесь зараженным и обязаны держать её на руке до конца игры.',
    isInfection: true,
    players: 11,
    ability: '',
  }, {
    id: 20,
    media: 'AgACAgQAAxkDAAIEH16eyzmvWyHw7OxY9PDLBQABZna9QwAC8aoxG6z4_FAr2O38wVtLiVA4thsABAEAAwIAA20AAz3EBQABGAQ',
    type: 'infection',
    name: 'Заражение!',
    description: 'Получив эту карту от другого игрока, вы становитесь зараженным и обязаны держать её на руке до конца игры.',
    isInfection: true,
    players: 11,
    ability: '',
  }, {
    id: 21,
    media: 'AgACAgQAAxkDAAIEIF6ey0_gnCT8x1u8eh9tz8J7RG3HAALPqjEbMx_9UM06NafDUnKc_ciVIl0AAwEAAwIAA20AA-NzAgABGAQ',
    type: 'infection',
    name: 'Заражение!',
    description: 'Получив эту карту от другого игрока, вы становитесь зараженным и обязаны держать её на руке до конца игры.',
    isInfection: true,
    players: 11,
    ability: '',
  }, {
    id: 22,
    media: 'AgACAgQAAxkDAAIEIV6ey1AikGnzGPHbvtlUBK3D1B-kAALFqjEbXCT8UKRmlHDr5gABjXC6fSNdAAMBAAMCAANtAAOxfwACGAQ',
    type: 'action',
    name: 'Огнемёт',
    description: 'Соседний игрок выбывает из игры.',
    withPlayers: true,
    players: 4,
    ability: '',
  }, {
    id: 23,
    media: 'AgACAgQAAxkDAAIEIl6ey2Xp2G8NugSmVZxE9de-r2UQAALPqjEbKw39UIget9qyuSasU376Il0AAwEAAwIAA20AAyENAQABGAQ',
    type: 'action',
    name: 'Огнемёт',
    description: 'Соседний игрок выбывает из игры.',
    withPlayers: true,
    players: 4,
    ability: '',
  }, {
    id: 24,
    media: 'AgACAgQAAxkDAAIEI16ey2dTn5JLxuO61io6PaUDLxnNAAL0qjEb58D1UHY29pXzwQwzmqO0GwAEAQADAgADbQADUrcFAAEYBA',
    type: 'action',
    name: 'Огнемёт',
    description: 'Соседний игрок выбывает из игры.',
    withPlayers: true,
    players: 6,
    ability: '',
  }, {
    id: 25,
    media: 'AgACAgQAAxkDAAIEJF6ey2lkj3uVmJljta1baGLJdzM4AAIgqzEb9Wv8UGVV1PJFteJvlR62GwAEAQADAgADbQAD_LMFAAEYBA',
    type: 'action',
    name: 'Огнемёт',
    description: 'Соседний игрок выбывает из игры.',
    withPlayers: true,
    players: 9,
    ability: '',
  }, {
    id: 26,
    media: 'AgACAgQAAxkDAAIEJV6ey2oFRTkBZWR8B8SINJzl9rMhAALwqjEbzsn9UPliCgttydfrHz5_I10AAwEAAwIAA20AA0KCAAIYBA',
    type: 'action',
    name: 'Огнемёт',
    description: 'Соседний игрок выбывает из игры.',
    withPlayers: true,
    players: 11,
    ability: '',
  }, {
    id: 27,
    media: 'AgACAgQAAxkDAAIEJl6ey2zJ6guUISOFG6WtcyMJENd1AAL7qjEbAuP8UMOIciIfZSvyJjLLIl0AAwEAAwIAA20AAysNAQABGAQ',
    type: 'action',
    name: 'Анализ',
    description: 'Посмотрите карты на руке соседнего игрока.',
    withPlayers: true,
    players: 5,
    ability: '',
  }, {
    id: 28,
    media: 'AgACAgQAAxkDAAIEJ16ey219zgKtKoXVuLxrbpGYvmBfAALSqjEbhAb9UNqVEBsQl0wByLbMIl0AAwEAAwIAA20AA6gOAQABGAQ',
    type: 'action',
    name: 'Анализ',
    description: 'Посмотрите карты на руке соседнего игрока.',
    withPlayers: true,
    players: 6,
    ability: '',
  }, {
    id: 29,
    media: 'AgACAgQAAxkDAAIEKF6ey25mDzM0kfq28zcHXUTyLbcUAALTqjEbuK39UItwwibU72e8Cvj4Il0AAwEAAwIAA20AAx0OAQABGAQ',
    type: 'action',
    name: 'Анализ',
    description: 'Посмотрите карты на руке соседнего игрока.',
    withPlayers: true,
    players: 9,
    ability: '',
  }, {
    id: 30,
    media: 'AgACAgQAAxkDAAIEKV6ey2-CHY2Y9kiTmYxzyrGgX_-FAAIVqzEbqc_9UMBm2mikPzUT3BbiIl0AAwEAAwIAA20AAxwNAQABGAQ',
    type: 'action',
    name: 'Топор',
    description: 'Сбросьте сыгранную на вас или на соседнего игрока карту "Карантин" или выложенную между вами карту "Заколоченная дверь"',
    withPlayers: true,
    players: 4,
    ability: '',
  }, {
    id: 31,
    media: 'AgACAgQAAxkDAAIEKl6ey3BGvK2CUP3MPiaFd7NXWw-_AALZqjEbl1r9UIukwYOZkIlWVai0GwAEAQADAgADbQAD17sFAAEYBA',
    type: 'action',
    name: 'Топор',
    description: 'Сбросьте сыгранную на вас или на соседнего игрока карту "Карантин" или выложенную между вами карту "Заколоченная дверь"',
    withPlayers: true,
    players: 9,
    ability: '',
  }, {
    id: 32,
    media: 'AgACAgQAAxkDAAIEK16ey4XMDiA7jLDvMicRPYlSKs4yAAIIqzEbM8_8UMkE6OziPVT9ozkII10AAwEAAwIAA20AA1mqAAIYBA',
    type: 'action',
    name: 'Подозрение',
    description: 'Посмотрите 1 случайную карту на руке соседнего игрока.',
    withPlayers: true,
    players: 4,
    ability: '',
  }, {
    id: 33,
    media: 'AgACAgQAAxkDAAIELF6ey4cRoMDCxyn-beuxdMV8BrYDAALtqjEblkv8UNiYwKbIO9gfwKnmIl0AAwEAAwIAA20AA-cNAQABGAQ',
    type: 'action',
    name: 'Подозрение',
    description: 'Посмотрите 1 случайную карту на руке соседнего игрока.',
    withPlayers: true,
    players: 4,
    ability: '',
  }, {
    id: 34,
    media: 'AgACAgQAAxkDAAIELV6ey4iGRvAVORTCAAHJ8pYyj_GWCgAC36oxG71A_VChstzWAX6kd6sqthsABAEAAwIAA20AA4K-BQABGAQ',
    type: 'action',
    name: 'Подозрение',
    description: 'Посмотрите 1 случайную карту на руке соседнего игрока.',
    withPlayers: true,
    players: 4,
    ability: '',
  }, {
    id: 35,
    media: 'AgACAgQAAxkDAAIELl6ey4nIcYsBmO6scZrIiA-KqRCfAALYqjEbSij1UFlEL5DVAUn2uMqVIl0AAwEAAwIAA20AA4pzAgABGAQ',
    type: 'action',
    name: 'Подозрение',
    description: 'Посмотрите 1 случайную карту на руке соседнего игрока.',
    withPlayers: true,
    players: 4,
    ability: '',
  }, {
    id: 36,
    media: 'AgACAgQAAxkDAAIEL16ey4pD7WHDyeKdBdxcVGQDfLFbAAIVqzEba3n9UNvByNeFTxi9I4HdIl0AAwEAAwIAA20AA8gLAQABGAQ',
    type: 'action',
    name: 'Подозрение',
    description: 'Посмотрите 1 случайную карту на руке соседнего игрока.',
    withPlayers: true,
    players: 7,
    ability: '',
  }, {
    id: 37,
    media: 'AgACAgQAAxkDAAIEMF6ey4uXbfwYYMZCJS9uiEEgBTRUAAL_qjEbz1L9UJ8R9WXCxaF1DPzbIl0AAwEAAwIAA20AA9wJAQABGAQ',
    type: 'action',
    name: 'Подозрение',
    description: 'Посмотрите 1 случайную карту на руке соседнего игрока.',
    withPlayers: true,
    players: 8,
    ability: '',
  }, {
    id: 38,
    media: 'AgACAgQAAxkDAAIEMV6ey4xGM5rKLStQWE7nAAGQh4J36wACsaoxG-9E_FAjNaahj3o9KMZ8ZiJdAAMBAAMCAANtAAPCfgEAARgE',
    type: 'action',
    name: 'Подозрение',
    description: 'Посмотрите 1 случайную карту на руке соседнего игрока.',
    withPlayers: true,
    players: 9,
    ability: '',
  }, {
    id: 39,
    media: 'AgACAgQAAxkDAAIEMl6ey42Bffk-ZF8ByI7_58Hc3fDPAALsqjEbBt_8UI4-8Z04GBHFAAGqtBsABAEAAwIAA20AA5LABQABGAQ',
    type: 'action',
    name: 'Подозрение',
    description: 'Посмотрите 1 случайную карту на руке соседнего игрока.',
    withPlayers: true,
    players: 10,
    ability: '',
  }, {
    id: 40,
    media: 'AgACAgQAAxkDAAIEM16ey6I4rvM3N9YsbqyiaTJmZuV7AAIFqzEbRQH1UH6LOUy6jLRO_TF8I10AAwEAAwIAA20AA_6AAAIYBA',
    type: 'action',
    name: 'Виски',
    description: 'Покажите все свои карты остальным игрокам. Эту карту можно сыграть только на себя.',
    withPlayers: true,
    players: 4,
    ability: '',
  }, {
    id: 41,
    media: 'AgACAgQAAxkDAAIENF6ey7duZGVTdzxb5M47yjoLBoogAAI5qzEbS7v8UPMt2BhnlNPmSMiVIl0AAwEAAwIAA20AA9txAgABGAQ',
    type: 'action',
    name: 'Виски',
    description: 'Покажите все свои карты остальным игрокам. Эту карту можно сыграть только на себя.',
    withPlayers: true,
    players: 6,
    ability: '',
  }, {
    id: 42,
    media: 'AgACAgQAAxkDAAIENV6ey7lkE5hVSrruFatoUsY9bne1AALfqjEb_lT8UNM5imqJd65HcwRoIl0AAwEAAwIAA20AA36CAQABGAQ',
    type: 'action',
    name: 'Виски',
    description: 'Покажите все свои карты остальным игрокам. Эту карту можно сыграть только на себя.',
    withPlayers: true,
    players: 10,
    ability: '',
  }, {
    id: 43,
    media: 'AgACAgQAAxkDAAIENl6ey7rPCUXFVuZQWbjgsWko0tj-AALlqjEbvt78UBhTdumXBGI4B6_eIV0AAwEAAwIAA20AA4jxAgABGAQ',
    type: 'action',
    name: 'Упорство!',
    description: 'Возьмите 3 карты событий, оставьте на руке 1 и сбросьте остальные 2. Затем сыграйте или сбросьте 1 карту.',
    withPlayers: true,
    players: 4,
    ability: '',
  }, {
    id: 44,
    media: 'AgACAgQAAxkDAAIEN16ey8_pKY_jMdRXly-7fp9Ar_oKAALfqjEbuzr9UK-uVoK2tXs9eHBjIl0AAwEAAwIAA20AA0p6AQABGAQ',
    type: 'action',
    name: 'Упорство!',
    description: 'Возьмите 3 карты событий, оставьте на руке 1 и сбросьте остальные 2. Затем сыграйте или сбросьте 1 карту.',
    withPlayers: true,
    players: 4,
    ability: '',
  }, {
    id: 45,
    media: 'AgACAgQAAxkDAAIEOF6ey9CO5zs_wsAuyu6SUivPs2I9AAIBqzEbDKH1UND9ibiJZmsyd6q0GwAEAQADAgADbQADCL0FAAEYBA',
    type: 'action',
    name: 'Упорство!',
    description: 'Возьмите 3 карты событий, оставьте на руке 1 и сбросьте остальные 2. Затем сыграйте или сбросьте 1 карту.',
    withPlayers: true,
    players: 6,
    ability: '',
  }, {
    id: 46,
    media: 'AgACAgQAAxkDAAIEOV6ey9FTcyQbarzEQQuuAYCxb1PYAAIpqzEbYz_1UGP1-FcsjHrDUC8FI10AAwEAAwIAA20AA0GpAAIYBA',
    type: 'action',
    name: 'Упорство!',
    description: 'Возьмите 3 карты событий, оставьте на руке 1 и сбросьте остальные 2. Затем сыграйте или сбросьте 1 карту.',
    withPlayers: true,
    players: 9,
    ability: '',
  }, {
    id: 47,
    media: 'AgACAgQAAxkDAAIEOl6ey9PWl0uTOI5Fk8MIawOzmzzhAAITqzEbz-L8UGLHGMno9K5b3HtmIl0AAwEAAwIAA20AA0t9AQABGAQ',
    type: 'action',
    name: 'Упорство!',
    description: 'Возьмите 3 карты событий, оставьте на руке 1 и сбросьте остальные 2. Затем сыграйте или сбросьте 1 карту.',
    withPlayers: true,
    players: 10,
    ability: '',
  }, {
    id: 48,
    media: 'AgACAgQAAxkDAAIEO16ey9b3KAfrkBs0tthCd1N73AYqAAK_qjEbRnD9UGZI2pDIelCepEW2GwAEAQADAgADbQADTb4FAAEYBA',
    type: 'action',
    name: 'Гляди по сторонам',
    description: 'Очередность хода передается в обратную сторону. Меняются порядок хода игроков и направление обмена картами с соседом.',
    withPlayers: true,
    players: 4,
    ability: '',
  }, {
    id: 49,
    media: 'AgACAgQAAxkDAAIEPF6ey9dbuKv_u9RqqblsMU6Ytf6eAALwqjEb33T9UCXENlwTZzWUuiW2GwAEAQADAgADbQADCLwFAAEYBA',
    type: 'action',
    name: 'Гляди по сторонам',
    description: 'Очередность хода передается в обратную сторону. Меняются порядок хода игроков и направление обмена картами с соседом.',
    withPlayers: true,
    players: 9,
    ability: '',
  }, {
    id: 50,
    media: 'AgACAgQAAxkDAAIEPV6ey9gyU9r0wszn1TapktARxGYwAAL0qjEbPOb8UI7MN02wmcgkM0G2GwAEAQADAgADbQADub4FAAEYBA',
    type: 'action',
    name: 'Меняемся местами!',
    description: 'Поменяйтесь местами с соседним игроком, если он не на карантине и не за заколоченной дверью',
    withPlayers: true,
    players: 4,
    ability: '',
  }, {
    id: 51,
    media: 'AgACAgQAAxkDAAIEPl6ey9pD_y19xr2oT1wGsBKg3tvBAAL3qjEbjar9UJGCa8hbdCLxL3H3Il0AAwEAAwIAA20AAx4PAQABGAQ',
    type: 'action',
    name: 'Меняемся местами!',
    description: 'Поменяйтесь местами с соседним игроком, если он не на карантине и не за заколоченной дверью',
    withPlayers: true,
    players: 4,
    ability: '',
  }, {
    id: 52,
    media: 'AgACAgQAAxkDAAIEP16ey9utWNc5Pbuc2U1bVf3AAAHOHgACW6sxG7-z9VC-1Q-xKGo8RPlRlyJdAAMBAAMCAANtAAPScwIAARgE',
    type: 'action',
    name: 'Меняемся местами!',
    description: 'Поменяйтесь местами с соседним игроком, если он не на карантине и не за заколоченной дверью',
    withPlayers: true,
    players: 7,
    ability: '',
  }, {
    id: 53,
    media: 'AgACAgQAAxkDAAIEQF6ey9zWwK64VPPEttFBXfJ-S-vgAALdqjEbMmf8UJN_cOYHtYADUqC0GwAEAQADAgADbQADwsYFAAEYBA',
    type: 'action',
    name: 'Меняемся местами!',
    description: 'Поменяйтесь местами с соседним игроком, если он не на карантине и не за заколоченной дверью',
    withPlayers: true,
    players: 9,
    ability: '',
  }, {
    id: 54,
    media: 'AgACAgQAAxkDAAIEQV6ey91lyiuNmW98seI34_1Lg4CVAALmqjEbBtz9UE3_9cEiTxBRwJu0GwAEAQADAgADbQADProFAAEYBA',
    type: 'action',
    name: 'Меняемся местами!',
    description: 'Поменяйтесь местами с соседним игроком, если он не на карантине и не за заколоченной дверью',
    withPlayers: true,
    players: 11,
    ability: '',
  }, {
    id: 55,
    media: 'AgACAgQAAxkDAAIEQl6ey94cry_dqMxNWIwFWY6yvokWAALzqjEb-Tb0UMV7DeyHQ3qo0joII10AAwEAAwIAA20AAwypAAIYBA',
    type: 'action',
    name: 'Сматывай удочки!',
    description: 'Поменяйтесь местами с любым игроком по вашему выбору, если он не на карантине. Игнорируйте все заколоченные двери.',
    withPlayers: true,
    players: 4,
    ability: '',
  }, {
    id: 56,
    media: 'AgACAgQAAxkDAAIEQ16ey_Q0bLLBXvjrFzK4EnIdMnjbAAIQqzEbnvv8UEdkureoXie8tpsAASNdAAMBAAMCAANtAAMXDAEAARgE',
    type: 'action',
    name: 'Сматывай удочки!',
    description: 'Поменяйтесь местами с любым игроком по вашему выбору, если он не на карантине. Игнорируйте все заколоченные двери.',
    withPlayers: true,
    players: 4,
    ability: '',
  }, {
    id: 57,
    media: 'AgACAgQAAxkDAAIERF6ey_X-DtZuFcj_lkvP0GEiVwPPAALGqjEbbq79UEwsiLaOspvVszHLIl0AAwEAAwIAA20AA98MAQABGAQ',
    type: 'action',
    name: 'Сматывай удочки!',
    description: 'Поменяйтесь местами с любым игроком по вашему выбору, если он не на карантине. Игнорируйте все заколоченные двери.',
    withPlayers: true,
    players: 7,
    ability: '',
  }, {
    id: 58,
    media: 'AgACAgQAAxkDAAIERV6ey_Zy8p3qYO7SpTsjRPg9vRIJAAKTqjEbsJv9UOmiAdTDnZSyIhX_Il0AAwEAAwIAA20AA7oMAQABGAQ',
    type: 'action',
    name: 'Сматывай удочки!',
    description: 'Поменяйтесь местами с любым игроком по вашему выбору, если он не на карантине. Игнорируйте все заколоченные двери.',
    withPlayers: true,
    players: 9,
    ability: '',
  }, {
    id: 59,
    media: 'AgACAgQAAxkDAAIERl6ezAvxXNUVy-RXajgmQJJpWenwAALsqjEbEXP8UJo0dUiuoJrggP8hGwAEAQADAgADbQADuDcHAAEYBA',
    type: 'action',
    name: 'Сматывай удочки!',
    description: 'Поменяйтесь местами с любым игроком по вашему выбору, если он не на карантине. Игнорируйте все заколоченные двери.',
    withPlayers: true,
    players: 11,
    ability: '',
  }, {
    id: 60,
    media: 'AgACAgQAAxkDAAIER16ezA0d7o-g9W68vrsO-tn2gr9OAAITqzEbTUX9UCldVxAKm_fTytMgGwAEAQADAgADbQAD_iQHAAEYBA',
    type: 'action',
    name: 'Соблазн',
    description: 'Поменяйтесь 1 картой с любым игроком по вашему выбору, если он не на карантине. Ваш ход заканчивается.',
    withPlayers: true,
    players: 4,
    ability: '',
  }, {
    id: 61,
    media: 'AgACAgQAAxkDAAIESF6ezA60K91uuKQOhJ27tbxPiqyrAAIuqzEb6D_8UE53xTOVZOR5qh-2GwAEAQADAgADbQADNrgFAAEYBA',
    type: 'action',
    name: 'Соблазн',
    description: 'Поменяйтесь 1 картой с любым игроком по вашему выбору, если он не на карантине. Ваш ход заканчивается.',
    withPlayers: true,
    players: 4,
    ability: '',
  }, {
    id: 62,
    media: 'AgACAgQAAxkDAAIESV6ezA8VUIONZRmOJDhbAcI-uCMEAALvqjEbitn9UC5iURz8lGso0cAJI10AAwEAAwIAA20AAxmlAAIYBA',
    type: 'action',
    name: 'Соблазн',
    description: 'Поменяйтесь 1 картой с любым игроком по вашему выбору, если он не на карантине. Ваш ход заканчивается.',
    withPlayers: true,
    players: 6,
    ability: '',
  }, {
    id: 63,
    media: 'AgACAgQAAxkDAAIESl6ezBDWoV3G0LnnEOdlDa1ZtuKLAAIfqzEb-_D9UCq3fwWZnGJPtTWRIl0AAwEAAwIAA20AA1F4AgABGAQ',
    type: 'action',
    name: 'Соблазн',
    description: 'Поменяйтесь 1 картой с любым игроком по вашему выбору, если он не на карантине. Ваш ход заканчивается.',
    withPlayers: true,
    players: 7,
    ability: '',
  }, {
    id: 64,
    media: 'AgACAgQAAxkDAAIES16ezBHDS01N-dwTF95j4zFzkzpeAALIqjEb2g_9UBTAPPeGZbtVksfPIl0AAwEAAwIAA20AAwMPAQABGAQ',
    type: 'action',
    name: 'Соблазн',
    description: 'Поменяйтесь 1 картой с любым игроком по вашему выбору, если он не на карантине. Ваш ход заканчивается.',
    withPlayers: true,
    players: 8,
    ability: '',
  }, {
    id: 65,
    media: 'AgACAgQAAxkDAAIETF6ezBSP3JNZ09SMAngAAYkY3-eRJQAC46oxGySn_VArFJlqZRKRzJKu3iFdAAMBAAMCAANtAANf8AIAARgE',
    type: 'action',
    name: 'Соблазн',
    description: 'Поменяйтесь 1 картой с любым игроком по вашему выбору, если он не на карантине. Ваш ход заканчивается.',
    withPlayers: true,
    players: 10,
    ability: '',
  }, {
    id: 66,
    media: 'AgACAgQAAxkDAAIETV6ezBVaqTcLIIAgSdRjSWdxAenBAALJqjEbBon8UE7fVJ3uoQiDLbQGI10AAwEAAwIAA20AA8WoAAIYBA',
    type: 'action',
    name: 'Соблазн',
    description: 'Поменяйтесь 1 картой с любым игроком по вашему выбору, если он не на карантине. Ваш ход заканчивается.',
    withPlayers: true,
    players: 11,
    ability: '',
  }, {
    id: 67,
    media: 'AgACAgQAAxkDAAIETl6ezBfO3L6YrSaW49OtimehpPeIAALbqjEbazD9UEG_P3JjC7kV4S0FI10AAwEAAwIAA20AAwmnAAIYBA',
    type: 'defence',
    name: 'Страх',
    description: 'Откажитесь от обмена картами и посмотрите карту, от которой отказались. Возьмите 1 карту события.',
    withPlayers: true,
    players: 5,
    ability: '',
  }, {
    id: 68,
    media: 'AgACAgQAAxkDAAIET16ezBeCCmhMJirkHwvWv0Mo19ofAAI5qzEbXpD0UEuQpALUU4njeO7YIl0AAwEAAwIAA20AA44RAQABGAQ',
    type: 'defence',
    name: 'Страх',
    description: 'Откажитесь от обмена картами и посмотрите карту, от которой отказались. Возьмите 1 карту события.',
    withPlayers: true,
    players: 6,
    ability: '',
  }, {
    id: 69,
    media: 'AgACAgQAAxkDAAIEUF6ezBjDqPTU-u4w8OGSNVgdAsHOAALOqjEb0nT9ULaOXJGw8FKjUVfxIl0AAwEAAwIAA20AAxmpAAIYBA',
    type: 'defence',
    name: 'Страх',
    description: 'Откажитесь от обмена картами и посмотрите карту, от которой отказались. Возьмите 1 карту события.',
    withPlayers: true,
    players: 8,
    ability: '',
  }, {
    id: 70,
    media: 'AgACAgQAAxkDAAIEUV6ezBvGL4wFcmrn-qGdJh2B8fdTAALDqjEbFP39UEv5PcBLZMu4VZzjIl0AAwEAAwIAA20AA_0MAQABGAQ',
    type: 'defence',
    name: 'Страх',
    description: 'Откажитесь от обмена картами и посмотрите карту, от которой отказались. Возьмите 1 карту события.',
    withPlayers: true,
    players: 11,
    ability: '',
  }, {
    id: 71,
    media: 'AgACAgQAAxkDAAIEUl6ezBzB7oXnwOqybq65DqjIxL7jAAL8qjEbKbL0UKd-3V_urpvdMCC2GwAEAQADAgADbQADebkFAAEYBA',
    type: 'defence',
    name: 'Мне и здесь не плохо',
    description: 'Отмените эффект карты "Меняемся местами!" или "Сматывай удочки!", если стали её целью. Возьмите 1 карту события.',
    withPlayers: true,
    players: 4,
    ability: '',
  }, {
    id: 72,
    media: 'AgACAgQAAxkDAAIEU16ezB5SJNfOwnqRG5L8tIu5TNTMAALhqjEbXsb8UOj5HqvpLsA7jHtmIl0AAwEAAwIAA20AA-l-AQABGAQ',
    type: 'defence',
    name: 'Мне и здесь не плохо',
    description: 'Отмените эффект карты "Меняемся местами!" или "Сматывай удочки!", если стали её целью. Возьмите 1 карту события.',
    withPlayers: true,
    players: 6,
    ability: '',
  }, {
    id: 73,
    media: 'AgACAgQAAxkDAAIEVF6ezB8bDWzVUZzD6_XIvqyUNRh5AAIdqzEbOG_0UCtVhSPlfx78v4a3GwAEAQADAgADbQADZMQFAAEYBA',
    type: 'defence',
    name: 'Мне и здесь не плохо',
    description: 'Отмените эффект карты "Меняемся местами!" или "Сматывай удочки!", если стали её целью. Возьмите 1 карту события.',
    withPlayers: true,
    players: 11,
    ability: '',
  }, {
    id: 74,
    media: 'AgACAgQAAxkDAAIEVV6ezCAW96h8Zx6MDLCMdcgDMxHEAAItqzEb8az0ULuietdtd1AhQap6I10AAwEAAwIAA20AA_x_AAIYBA',
    type: 'defence',
    name: 'Нет уж, спасибо!',
    description: 'Откажитесь от обмена картами. Возьмите 1 карту события.',
    withPlayers: true,
    players: 4,
    ability: '',
  }, {
    id: 75,
    media: 'AgACAgQAAxkDAAIEVl6ezCHIXDvMx-pPZy_TLvviGe-gAALjqjEbAQH9UJqlf5Kv2DDQPX_6Il0AAwEAAwIAA20AAxoOAQABGAQ',
    type: 'defence',
    name: 'Нет уж, спасибо!',
    description: 'Откажитесь от обмена картами. Возьмите 1 карту события.',
    withPlayers: true,
    players: 6,
    ability: '',
  }, {
    id: 76,
    media: 'AgACAgQAAxkDAAIEV16ezCKp9XO92KCOgOEMKuPSjBkAA86qMRvtav1Q6iQEDt_DKejG77cbAAQBAAMCAANtAAPCuQUAARgE',
    type: 'defence',
    name: 'Нет уж, спасибо!',
    description: 'Откажитесь от обмена картами. Возьмите 1 карту события.',
    withPlayers: true,
    players: 8,
    ability: '',
  }, {
    id: 77,
    media: 'AgACAgQAAxkDAAIEWF6ezDgk8jO-Pz_5GzbmUYT-f0uZAALoqjEbnnD9UO3gFUmKN50Y6Pb4Il0AAwEAAwIAA20AA3MOAQABGAQ',
    type: 'defence',
    name: 'Нет уж, спасибо!',
    description: 'Откажитесь от обмена картами. Возьмите 1 карту события.',
    withPlayers: true,
    players: 11,
    ability: '',
  }, {
    id: 78,
    media: 'AgACAgQAAxkDAAIEWV6ezDj3hjbymFfGXh8z3q31en8MAAL7qjEbOJr9UI737fWgSE3AzJsAASNdAAMBAAMCAANtAAPkDAEAARgE',
    type: 'defence',
    name: 'Мимо!',
    description: 'Откажитесь от обмена картами. Вместо вас картами меняется следующий за вами игрок. Возьмите 1 карту события.',
    withPlayers: true,
    players: 4,
    ability: '',
  }, {
    id: 79,
    media: 'AgACAgQAAxkDAAIEWl6ezE7icAO7ge98g1tDVSyZ4k9aAALsqjEbYyb8UEZcxUEL__RJVMXPIl0AAwEAAwIAA20AA80OAQABGAQ',
    type: 'defence',
    name: 'Мимо!',
    description: 'Откажитесь от обмена картами. Вместо вас картами меняется следующий за вами игрок. Возьмите 1 карту события.',
    withPlayers: true,
    players: 6,
    ability: '',
  }, {
    id: 80,
    media: 'AgACAgQAAxkDAAIEW16ezE90mYyZJ8Pi2P87K6f9wCi3AALZqjEb7Sj9UC1g7HBo11SCCvf4Il0AAwEAAwIAA20AA7ANAQABGAQ',
    type: 'defence',
    name: 'Мимо!',
    description: 'Откажитесь от обмена картами. Вместо вас картами меняется следующий за вами игрок. Возьмите 1 карту события.',
    withPlayers: true,
    players: 11,
    ability: '',
  }, {
    id: 81,
    media: 'AgACAgQAAxkDAAIEXF6ezFBXnu9JAaqDcHDjUw3EeM9xAAIfqzEbUZf0UOGJ_-9lXXF_Bi4FI10AAwEAAwIAA20AAzOlAAIYBA',
    type: 'defence',
    name: 'Никакого шашлыка!',
    description: 'Отмените эффект карты "Огнемет", если стали её целью. Возьмите 1 карту события.',
    withPlayers: true,
    players: 4,
    ability: '',
  }, {
    id: 82,
    media: 'AgACAgQAAxkDAAIEXV6ezFG6hX2ZSdgDnkV5q6B_z7riAAK8qjEbIjz9UNs6G5PcorLiUqi0GwAEAQADAgADbQADpsEFAAEYBA',
    type: 'defence',
    name: 'Никакого шашлыка!',
    description: 'Отмените эффект карты "Огнемет", если стали её целью. Возьмите 1 карту события.',
    withPlayers: true,
    players: 6,
    ability: '',
  }, {
    id: 83,
    media: 'AgACAgQAAxkDAAIEXl6ezGfklTV2aHOPAmMpMwqVFhdYAAIRqzEbt_z9UGuImJE_RrPVvqO0GwAEAQADAgADbQADBr4FAAEYBA',
    type: 'defence',
    name: 'Никакого шашлыка!',
    description: 'Отмените эффект карты "Огнемет", если стали её целью. Возьмите 1 карту события.',
    withPlayers: true,
    players: 11,
    ability: '',
  }, {
    id: 84,
    media: 'AgACAgQAAxkDAAIEX16ezGiwYxMuhQABmMTFFmqaoWW6CwAC_qoxG4Hs_VCHbMDOKnp4L1aJtxsABAEAAwIAA20AA_i7BQABGAQ',
    type: 'map',
    name: 'Карантин',
    description: 'Сыграйте эту карту на себя или на соседнего игрока. Следующие три своих хода игрок на карантине не может меняться картами, играть карты событий или становиться целью таких карт.',
    withPlayers: true,
    players: 5,
    ability: '',
  }, {
    id: 85,
    media: 'AgACAgQAAxkDAAIEYF6ezH1T6lWFdalio-ZM4_ZSYiWaAAIDqzEbcKH9UBxiaH1W_Z34sYiGIl0AAwEAAwIAA20AAzN6AgABGAQ',
    type: 'map',
    name: 'Карантин',
    description: 'Сыграйте эту карту на себя или на соседнего игрока. Следующие три своих хода игрок на карантине не может меняться картами, играть карты событий или становиться целью таких карт.',
    withPlayers: true,
    players: 9,
    ability: '',
  }, {
    id: 86,
    media: 'AgACAgQAAxkDAAIEYV6ezH4kM96ma5CxWNPthdZPXCOHAAK1qjEbVXr9UMmZRZPq_P_ZYa3eIV0AAwEAAwIAA20AA1PzAgABGAQ',
    type: 'map',
    name: 'Заколоченная дверь',
    description: 'Положите эту карту между собой и соседним игроком. Между вами не может совершаться никаких действий и обменов.',
    withPlayers: true,
    players: 4,
    ability: '',
  }, {
    id: 87,
    media: 'AgACAgQAAxkDAAIEYl6ezIDD2IPc8lNOmMMDYWIQmxjfAAL3qjEb-dv9UK3ZS1ZepOdlAdAMI10AAwEAAwIAA20AA1upAAIYBA',
    type: 'map',
    name: 'Заколоченная дверь',
    description: 'Положите эту карту между собой и соседним игроком. Между вами не может совершаться никаких действий и обменов.',
    withPlayers: true,
    players: 7,
    ability: '',
  }, {
    id: 88,
    media: 'AgACAgQAAxkDAAIEY16ezIDhnH3OA-y7Pis2I1bW75dkAALZqjEb52P9UJvIKv_uNNz-jWb0Il0AAwEAAwIAA20AA82lAAIYBA',
    type: 'map',
    name: 'Заколоченная дверь',
    description: 'Положите эту карту между собой и соседним игроком. Между вами не может совершаться никаких действий и обменов.',
    withPlayers: true,
    players: 11,
    ability: '',
  }, {
    id: 89,
    media: 'AgACAgQAAxkDAAIEZF6ezIFn2f_o30s77yfFZwiWTBAzAAL2qjEbOR38UMAKPWqq78xWSGT0Il0AAwEAAwIAA20AA8KnAAIYBA',
    type: 'panic',
    name: 'Старые веревки',
    description: 'Эти никчемные веревки рвутся от простого чиха! Все сыгранные карты "Карантин" сбрасываются.',
    withPlayers: false,
    players: 6,
    ability: 'drop_karantin'
  }, {
    id: 90,
    media: 'AgACAgQAAxkDAAIEZV6ezIM_KXDKLJn7atZAjK8uET_pAAL0qjEbpFL8UMzv5m4bTUcMESm2GwAEAQADAgADbQADV7oFAAEYBA',
    type: 'panic',
    name: 'Старые веревки',
    description: 'Эти никчемные веревки рвутся от простого чиха! Все сыгранные карты "Карантин" сбрасываются.',
    withPlayers: false,
    players: 9,
    ability: 'drop_karantin'
  }, {
    id: 91,
    media: 'AgACAgQAAxkDAAIEZl6ezIS2dyM3M_UuVvGm8VnumTcAA-SqMRsvmP1QhHTu4JzI68zhpQMjXQADAQADAgADbQADdKkAAhgE',
    type: 'panic',
    name: 'Раз, два...',
    description: `...Нечто поднялось со дна!\n\nПоменяйтесь местами с третьим от вас игроком слева или справа (по вашему выбору). Игнорируйте все заколоченные двери. Если игрок на карантине, смены мест не происходит.`,
    withPlayers: true,
    players: 5,
    ability: 'change_place ignore_doors',
    distance: [3,-3]
  }, {
    id: 92,
    media: 'AgACAgQAAxkDAAIEZ16ezIWPuvuILaRsPFmR5TRsYLZlAAIdqzEbwcD9UNSqfy-PykuVv_zbIl0AAwEAAwIAA20AA4YNAQABGAQ',
    type: 'panic',
    name: 'Раз, два...',
    description: `...Нечто поднялось со дна!\n\nПоменяйтесь местами с третьим от вас игроком слева или справа (по вашему выбору). Игнорируйте все заколоченные двери. Если игрок на карантине, смены мест не происходит.`,
    withPlayers: true,
    players: 9,
    ability: 'change_place ignore_doors',
    distance: [3,-3]
  }, {
    id: 93,
    media: 'AgACAgQAAxkDAAIEaF6ezIZ9Eg7iErjRhgcKFCQRIeLRAAIJqzEb6Hb8UHu479zMZEHvBz-2GwAEAQADAgADbQADx7oFAAEYBA',
    type: 'panic',
    name: '...ТРИ, ЧЕТЫРЕ...',
    description: `...открывайте дверь пошире!\n\nВсе сыгранные карты "Заколоченная дверь" сбрасываются.`,
    withPlayers: false,
    players: 4,
    ability: 'drop_doors'
  }, {
    id: 94,
    media: 'AgACAgQAAxkDAAIEaV6ezIcvgdsKYp_LtUPBFOwk5gHFAAL8qjEbXHj8ULvrrE645eNEcbDeIV0AAwEAAwIAA20AA5z1AgABGAQ',
    type: 'panic',
    name: '...ТРИ, ЧЕТЫРЕ...',
    description: `...открывайте дверь пошире!\n\nВсе сыгранные карты "Заколоченная дверь" сбрасываются.`,
    withPlayers: false,
    players: 9,
    ability: 'drop_doors'
  }, {
    id: 95,
    type: 'panic',
    media: 'AgACAgQAAxkDAAIEal6ezIka7ueaOulPwQXpuiP4z-sYAALcqjEbVBX9UGIKmIkdhkq2R1nUIl0AAwEAAwIAA20AAwEQAQABGAQ',
    description: `Все сыгранные карты "Карантин" и "Заколоченная дверь" сбрасываются. Затем, начиная с вас и по часовой стрелке, все игроки парами меняются местами.\n\nВ случае нечетного числа игроков, последний игрок остается на месте`,
    withPlayers: true,
    players: 5,
    ability: 'drop_karantin drop_doors change_place_pairs'
  }, {
    id: 96,
    media: 'AgACAgQAAxkDAAIEa16ezIuDBEtRI4CqAAEGd_IH1wY23AACHqsxG29X_VB1ywFsCouBH0uptBsABAEAAwIAA20AA3vKBQABGAQ',
    type: 'panic',
    name: 'И это вы называете вечеринкой?',
    description: `Все сыгранные карты "Карантин" и "Заколоченная дверь" сбрасываются. Затем, начиная с вас и по часовой стрелке, все игроки парами меняются местами.\n\nВ случае нечетного числа игроков, последний игрок остается на месте`,
    withPlayers: true,
    players: 9,
    ability: 'drop_karantin drop_doors change_place_pairs'
  }, {
    id: 97,
    media: 'AgACAgQAAxkDAAIEbF6ezIz7oqOKzd97Tp39qgO5l6S5AALwqjEbwHX9UI74aycHKzvIUyqOIl0AAwEAAwIAA20AA-R5AgABGAQ',
    type: 'panic',
    name: 'Убирайся прочь!',
    description: 'Поменяйся местами с любым игроком (по вашему выбору), если он не на карантине.',
    withPlayers: true,
    players: 5,
    ability: 'change_place',
    distance: [12]
  }, {
    id: 98,
    media: 'AgACAgQAAxkDAAIEbV6ezKG8WGEmTdJUjNb50slJGdLMAALvqjEbiq_9UPk0gy8AAezUGoX82yJdAAMBAAMCAANtAAN9DwEAARgE',
    type: 'panic',
    name: 'Забывчивость',
    description: 'Сбросьте 3 карты с руки и возьмите 3 новые карты событий. Сбрасывайте все попадающиеся карты паники.',
    withPlayers: false,
    players: 4,
    ability: 'fold_cards_3 with_deck skip_panic',
    distance: [0]
  }, {
    id: 99,
    media: 'AgACAgQAAxkDAAIEe16ezUtCRU0dQswfg9M8PHVHWQ7tAAI3qzEb1t71UDAC_LVvDD1jLpi3GwAEAQADAgADbQADsbsFAAEYBA',
    type: 'panic',
    name: 'Цепная реакция',
    description: `Каждый игрок одновременно с остальными отдает 1 карту следующему по порядку хода игроку, игнорируя все сыгранные карты "Карантин" и "Заколоченная дверь".\n\nВы не можете отказаться от получения карты при помощи других карт.\n\n"Нечто" может заразить другого игрока, передав ему карту "Заражение!".\n\nВаш ход заканчивается.
    `,
    noMove: true,
    players: 4,
    withPlayers: true, 
    ability: 'change_card ignore_karantin ignore_doors',
  }, {
    id: 100,
    media: 'AgACAgQAAxkDAAIEe16ezUtCRU0dQswfg9M8PHVHWQ7tAAI3qzEb1t71UDAC_LVvDD1jLpi3GwAEAQADAgADbQADsbsFAAEYBA',
    type: 'panic',
    name: 'Цепная реакция',
    description: `Каждый игрок одновременно с остальными отдает 1 карту следующему по порядку хода игроку, игнорируя все сыгранные карты "Карантин" и "Заколоченная дверь".\n\nВы не можете отказаться от получения карты при помощи других карт.\n\n"Нечто" может заразить другого игрока, передав ему карту "Заражение!".\n\nВаш ход заканчивается.
    `,
    noMove: true,
    players: 9,
    withPlayers: true, 
    ability: 'change_card ignore_karantin ignore_doors',
    distance: [1]
  }, {
    id: 101,
    media: 'AgACAgQAAxkDAAIEfF6ezUuxZJ_G3H2OPkkcW0G_042cAAIFqzEbAt71UOF-U6bU_XxSnbrMIl0AAwEAAwIAA20AA6MNAQABGAQ',
    type: 'panic',
    name: 'Давай дружить?',
    description: 'Поменяйтесь 1 картой с любым игроком (по вашему выбору), если он не на карантине.',
    players: 7,
    withPlayers: true,
    ability: 'change_card',
    distance: [12]
  }, {
    id: 102,
    media: 'AgACAgQAAxkDAAIEfV6ezUufaPoxAXdT76t0CC-Ue0bVAAK1qjEbVlr9ULXYiz0jlnmBwKnJIl0AAwEAAwIAA20AA1gNAQABGAQ',
    type: 'panic',
    name: 'Давай дружить?',
    description: 'Поменяйтесь 1 картой с любым игроком (по вашему выбору), если он не на карантине.',
    players: 9,
    withPlayers: true,
    ability: 'change_card',
    distance: [12]
  }, {
    id: 103,
    media: 'AgACAgQAAxkDAAIEfl6ezUzZK0wlp3i_X2x5szrDUOETAALMqjEbBJf8UBuzMb1aMrzpe6YDI10AAwEAAwIAA20AAxupAAIYBA',
    type: 'panic',
    name: 'Свидание вслепую',
    description: 'Поменяйте 1 карту с руки на верхнюю карту общей колоды, сбрасывая все попадающиеся карты паники. Ваш ход заканчивается.',
    noMove: true,
    withPlayers: false,
    players: 4,
    ability: 'change_card with_deck skip_panic',
    defence: [0]
  }, {
    id: 104,
    media: 'AgACAgQAAxkDAAIEf16ezUwQ-1kthEcvuiYVfGACJPvkAALlqjEbe_r8UONmD-m-87yQAZa3GwAEAQADAgADbQADpsYFAAEYBA',
    type: 'panic',
    name: 'Свидание вслепую',
    description: 'Поменяйте 1 карту с руки на верхнюю карту общей колоды, сбрасывая все попадающиеся карты паники. Ваш ход заканчивается.',
    noMove: true,
    withPlayers: false,
    players: 9,
    ability: 'change_card with_deck skip_panic',
    defence: [0],
  }, {
    id: 105,
    media: 'AgACAgQAAxkDAAIEgF6ezU3_ll1EwO8Q418IIokzIadVAAL8qjEbhFr8UEa1_68NPOZFOvG3GwAEAQADAgADbQADh8MFAAEYBA',
    type: 'panic',
    name: 'Уупс!',
    description: 'Покажите все свои карты на руке остальным игрокам.',
    withPlayers: true,
    players: 10,
    ability: 'show_cards',
    distance: [12]
  }, {
    id: 106,
    media: 'AgACAgQAAxkDAAIEgV6ezU1PlajjTfdfCGjpE73xxSFmAALmqjEb3Sj8UKGrTzsj3C32t6zJIl0AAwEAAwIAA20AA5MNAQABGAQ',
    type: 'panic',
    name: 'Только между нами...',
    description: 'Покажите все карты на руке соседнему игроку на ваш выбор.',
    withPlayers: true,
    players: 7,
    ability: 'show_cards',
    distance: [1,-1]
  }, {
    id: 107,
    media: 'AgACAgQAAxkDAAIEgl6ezU09j0GQCHsKHYT7zapYxNNGAAL8qjEboYj8UGeISftd3DWzGSd5I10AAwEAAwIAA20AA4p_AAIYBA',
    type: 'panic',
    name: 'Только между нами...',
    description: 'Покажите все карты на руке соседнему игроку на ваш выбор.',
    withPlayers: true,
    players: 9,
    ability: 'show_cards',
    distance: [1,-1]
  }, {
    id: 108,
    media: 'AgACAgQAAxkDAAIEg16ezU6LfAbFu4edBBUnNsCKiim_AAL7qjEb1Rf8UOBe4uQtQJhQt6UDI10AAwEAAwIAA20AA1SoAAIYBA',
    type: 'panic',
    name: 'Время признаний',
    description: `Начиная с вас и по порядку хода, каждый игрок либо показывает, либо не показывает все карты на руке остальным игрокам.\n\nВремя признаний заканчивается, когда кто-то из игроков показывает карту "Заражение!", при этом нет необходимости показывать остальные карты на руке.`,
    withPlayers: true,
    players: 8,
    isCommon: true,
    isCircular: 1,
    ability: 'show_cards',
  }, {
    id: 109,
    isPanic: false,
    media: 'AgACAgQAAxkDAAIEhF6ezU5C_Er4_tnQYMvBgtVYg0ibAAJJqzEbDEX1UOsFQwvD5TOTbzR8I10AAwEAAwIAA20AA8t-AAIYBA',
    type: 'action',
    name: 'Некрономикон',
    description: 'Любой выбранный игрок выбывает из игры',
    withPlayers: true,
    players: 10,
    ability: 'kill',
    distance: [12]
  }, {
    id: 110,
    isPanic: false,
    media: 'AgACAgQAAxkDAAIEhV6ezU78U9Futw4zdqfABYicBJJTAAJAqzEbziv1UDkYGto0WwR-C0zRIl0AAwEAAwIAA20AA4gNAQABGAQ',
    type: 'action',
    name: 'Г.Ф.Лавкрафт',
    description: 'Посмотрите карты на руке любого выбранного игрока.',
    withPlayers: true,
    players: 6,
    ability: 'show_cards'
  }
]

module.exports = cards